In [1]:
#!pip install pycaret

from pycaret.utils import version
version()

import warnings
warnings.filterwarnings('ignore')

import pandas as pd
import numpy as np

1.0.0

In [2]:
train = pd.read_csv("../data/loan_prediction_train.csv")

In [3]:
print(train.shape)
train.head()

(614, 13)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [4]:
from pycaret import classification

In [5]:
classification_setup = classification.setup(data= train, target='Loan_Status')

Setup Succesfully Completed!

In [6]:
classification_dt = classification.create_model('dt')

      Accuracy     AUC  Recall   Prec.      F1   Kappa
0       0.8140  0.7359  0.9333  0.8235  0.8750  0.5169
1       0.7907  0.7192  0.9000  0.8182  0.8571  0.4691
2       0.8140  0.7141  0.9667  0.8056  0.8788  0.4926
3       0.7907  0.7628  0.8333  0.8621  0.8475  0.5144
4       0.8140  0.7359  0.9333  0.8235  0.8750  0.5169
5       0.7209  0.6638  0.8276  0.7742  0.8000  0.3402
6       0.7442  0.6810  0.8621  0.7812  0.8197  0.3833
7       0.7674  0.7352  0.8276  0.8276  0.8276  0.4704
8       0.7209  0.6638  0.8276  0.7742  0.8000  0.3402
9       0.8333  0.7732  0.9310  0.8438  0.8852  0.5836
Mean    0.7810  0.7185  0.8843  0.8134  0.8466  0.4628
SD      0.0387  0.0364  0.0517  0.0281  0.0311  0.0778

In [7]:
classification_xgb = classification.create_model('xgboost')

      Accuracy     AUC  Recall   Prec.      F1   Kappa
0       0.7907  0.7692  0.9333  0.8000  0.8615  0.4432
1       0.7442  0.7359  0.8667  0.7879  0.8254  0.3512
2       0.7907  0.6744  0.9667  0.7838  0.8657  0.4145
3       0.8140  0.7744  0.9667  0.8056  0.8788  0.4926
4       0.8372  0.7385  1.0000  0.8108  0.8955  0.5446
5       0.8372  0.7549  1.0000  0.8056  0.8923  0.5743
6       0.7442  0.7315  0.8966  0.7647  0.8254  0.3582
7       0.8140  0.7217  0.9310  0.8182  0.8710  0.5426
8       0.8372  0.7906  1.0000  0.8056  0.8923  0.5743
9       0.8333  0.7401  0.9655  0.8235  0.8889  0.5638
Mean    0.8043  0.7431  0.9526  0.8006  0.8697  0.4859
SD      0.0345  0.0308  0.0432  0.0166  0.0248  0.0835

In [ ]:
tune_catboost = classification.tune_model('catboost',n_iter=50, optimize='AUC')

IntProgress(value=0, description='Processing: ', max=16)

Initiated  . . . . . . . . . . . . . . . . . .                13:11:17
Status     . . . . . . . . . . . . . . . . . .  Tuning Hyperparameters
ETC        . . . . . . . . . . . . . . . . . .         Calculating ETC

Empty DataFrame
Columns: [Accuracy, AUC, Recall, Prec., F1, Kappa]
Index: []

In [ ]:
boosting = classification.ensemble_model(classification_dt, method= 'Boosting')

In [ ]:
blender = classification.blend_models(estimator_list=[classification_dt, classification_xgb])

In [ ]:
classification.compare_models()

In [ ]:
# AUC-ROC plot
classification.plot_model(classification_dt, plot = 'auc')

In [ ]:
# Validation Curve
classification.plot_model(classification_dt, plot = 'vc')

In [ ]:
# Dimension Learning
classification.plot_model(classification_xgb, plot = 'feature')

In [ ]:
# Confusion Matrix
classification.plot_model(classification_dt, plot = 'confusion_matrix')

In [ ]:
classification.evaluate_model(classification_dt)

In [ ]:
classification.interpret_model(classification_dt)

In [ ]:
test = pd.read_csv('../data/loan_prediction_test.csv')

In [ ]:
predictions = classification.predict_model(classification_dt, data=test)

In [ ]:
predictions.head()

In [ ]:
classification.save_model(classification_dt, 'decision_tree_1')